name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker services
        run: |
          docker compose version
          docker compose up -d provue-postgres

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Cache Next.js build artifacts
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('package-lock.json', 'next.config.js', 'tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Run format check
        run: npm run format

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm test -- --runInBand

      - name: Build project
        run: npm run build

      - name: Tear down Docker services
        if: always()
        run: docker compose down
